<a href="https://colab.research.google.com/github/venkatesh58285/ML/blob/main/Lab1_AP23110011217.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
import numpy as np

chessboard = np.zeros((10, 10), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1

print(chessboard)



[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [ ]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
import numpy as np
A = np.zeros((1000,1000),dtype=np.float64).reshape((1000,1000))
print(A.nbytes) #bytes
print(A.nbytes/1024**2) #mb

8000000
7.62939453125


[link text](https://)## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [ ]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a[[0, -1]] = a[[-1, 0]]

print(a)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [ ]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
import numpy as np

# Create a 3D array
a = np.arange(2*3*4).reshape((2, 3, 4))
print("Original array (a):")
print(a)

# Using ravel() – returns a view (if possible)
r = a.ravel()
print("\nUsing ravel():")
print(r)

# Using flatten() – always returns a copy
f = a.flatten()
print("\nUsing flatten():")
print(f)


Original array (a):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Using ravel():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Using flatten():
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


In [ ]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
import numpy as np
ab = np.arange(10)
split_ab = np.array_split(ab,2) #can split unevenly as well
a = split_ab[0]
b = split_ab[1]
print(a)
print(b)


[0 1 2 3 4]
[5 6 7 8 9]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [ ]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
degrees = np.array([0,30,45,60,90])
rads = np.deg2rad(degrees)
print('rads',rads)
print('sin values',np.sin(rads))


rads [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin values [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [ ]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
import numpy as np

row = np.arange(1, 11)         # shape: (10,)
col = np.arange(1, 11).reshape(10, 1)  # shape: (10, 1)

table = col * row

print("10×10 Multiplication Table:")
print(table)



10×10 Multiplication Table:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [ ]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.

percentiles = np.percentile(data.flatten(), [25, 50, 75])
print("25th, 50th, and 75th percentiles of flattened data:", percentiles)

25th, 50th, and 75th percentiles of flattened data: [30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


In [ ]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rng = np.random.default_rng() # Using a new random number generator instance
num_rolls = 100
rolls = rng.integers(1, 7, size=num_rolls) # Simulate 100 rolls (integers from 1 to 6 inclusive)

# Count the number of 6s
num_sixes = np.sum(rolls == 6)

# Estimate the proportion of 6s
proportion_sixes = num_sixes / num_rolls

print(f"Number of rolls: {num_rolls}")
print(f"Number of 6s: {num_sixes}")
print(f"Estimated proportion of 6s: {proportion_sixes:.4f}")

Number of rolls: 100
Number of 6s: 25
Estimated proportion of 6s: 0.2500


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [ ]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib.recfunctions import append_fields

# Sample height data (replace with actual data)
height_data = np.array([165.5, 180.0], dtype='f4') # Example heights for Alice and Bob

# Append the 'height' field
people_with_height = append_fields(people, 'height', height_data, usemask=False)

print("Structured array with 'height' field:")
display(people_with_height)



Structured array with 'height' field:


array([('Alice', 25, 55. , 165.5), ('Bob', 30, 85.5, 180. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4'), ('height', '<f4')])

## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [ ]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues of A:")
print(eigenvalues)
# You can also print eigenvectors if needed:
# print("\nEigenvectors of A:")
# print(eigenvectors)

Eigenvalues of A:
[ 1.48615964  0.62761295 -0.10858378]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [ ]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
file_path = 'data.csv'
np.savetxt(file_path, data, delimiter=',')
print(f"Data saved to {file_path}")

# Load data from the CSV file
loaded_data = np.loadtxt(file_path, delimiter=',')
print(f"\nData loaded from {file_path}:")
print(loaded_data)

# Verify that the loaded data is the same as the original data
print("\nLoaded data equals original data?", np.allclose(loaded_data, data))


Data saved to data.csv

Data loaded from data.csv:
[[85. 64. 51. 27.]
 [31.  5.  8.  2.]
 [18. 81. 65. 91.]
 [50. 61. 97. 73.]
 [63. 54. 56. 93.]]

Loaded data equals original data? True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [ ]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
mondays_count = np.sum(dates.astype('datetime64[W]').astype(int) == 0)

print(f"The 'dates' array contains {mondays_count} Mondays.")

The 'dates' array contains 0 Mondays.


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [ ]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
data_with_nan = np.array([[1, 2, np.nan, 4],
                          [5, np.nan, 7, 8],
                          [9, 10, 11, np.nan],
                          [13, 14, 15, 16]])

print("Original array with NaNs:")
print(data_with_nan)


Original array with NaNs:
[[ 1.  2. nan  4.]
 [ 5. nan  7.  8.]
 [ 9. 10. 11. nan]
 [13. 14. 15. 16.]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [44]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [45]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
import datetime

# 1. Ensure the 'date' column is datetime64
# Convert the string dates to datetime64 using datetime.strptime and specifying the format
converted_dates = []
# Assuming the format is 'MM-DD-YYYY' based on the previous error
date_format = '%m-%d-%Y'
for d_str in fitness['date']:
    try:
        dt_obj = datetime.datetime.strptime(d_str, date_format)
        converted_dates.append(np.datetime64(dt_obj))
    except ValueError:
        # If 'MM-DD-YYYY' fails, try 'DD-MM-YYYY'
        date_format = '%d-%m-%Y'
        dt_obj = datetime.datetime.strptime(d_str, date_format)
        converted_dates.append(np.datetime64(dt_obj))


fitness['date'] = np.array(converted_dates, dtype='datetime64[D]')
# 2. Extract the month and 3. Group by month
# Create a new array with month and year for grouping
months = fitness['date'].astype('datetime64[M]')

# Use np.unique to get unique months and their indices
unique_months, month_indices = np.unique(months, return_inverse=True)

# 4. Calculate the sum of 'step_count' for each month
monthly_step_count = np.bincount(month_indices, weights=fitness['step_count'])

# 5. Print the monthly step count analysis results
print("Monthly Step Count:")
for i, month in enumerate(unique_months):
    print(f"{month.astype('datetime64[M]').item().strftime('%Y-%m')}: {monthly_step_count[i]:.0f}")

Monthly Step Count:
2017-06: 5464
2017-07: 6041
2017-08: 25
2017-09: 5461
2017-10: 53175
2017-11: 107616
2017-12: 93905
2018-01: 10163


In [46]:
# 1. Extract the 'hours_of_sleep' and 'mood' columns
hours_of_sleep = fitness['hours_of_sleep']
mood = fitness['mood']

# 2. Calculate the Pearson correlation coefficient
# np.corrcoef returns a 2x2 matrix, the off-diagonal elements are the correlation coefficients
correlation_matrix = np.corrcoef(hours_of_sleep, mood)
correlation_coefficient = correlation_matrix[0, 1]

# 3. Print the calculated correlation coefficient
print(f"Correlation coefficient between hours of sleep and mood: {correlation_coefficient:.4f}")

Correlation coefficient between hours of sleep and mood: 0.2104


In [47]:
# 1. Extract the required columns
dates = fitness['date']
step_counts = fitness['step_count']
calories_burned = fitness['calories_burned']
hours_of_sleep = fitness['hours_of_sleep']

# 2. Convert the 'date' column to datetime64[W] to group data by week
weekly_dates = dates.astype('datetime64[W]')

# 3. Use np.unique with return_inverse=True on the weekly dates
unique_weeks, week_indices = np.unique(weekly_dates, return_inverse=True)

# 4. Calculate the sum of 'step_count' and 'calories_burned' for each week
weekly_step_count = np.bincount(week_indices, weights=step_counts)
weekly_calories_burned = np.bincount(week_indices, weights=calories_burned)

# 5. Calculate the average of 'hours_of_sleep' for each week
weekly_sleep_sum = np.bincount(week_indices, weights=hours_of_sleep)
weekly_counts = np.bincount(week_indices) # Count of entries per week
weekly_sleep_avg = weekly_sleep_sum / weekly_counts

# 6. Iterate through the unique weeks and print the weekly summary
print("Weekly Fitness Summary:")
for i, week_start_date in enumerate(unique_weeks):
    # Format the week start date for readability (e.g., YYYY-MM-DD)
    formatted_date = week_start_date.astype(datetime.datetime).strftime('%Y-%m-%d')
    print(f"Week starting {formatted_date}:")
    print(f"  Total Steps: {weekly_step_count[i]:.0f}")
    print(f"  Total Calories Burned: {weekly_calories_burned[i]:.0f}")
    print(f"  Average Hours of Sleep: {weekly_sleep_avg[i]:.2f}\n")

Weekly Fitness Summary:
Week starting 2017-06-08:
  Total Steps: 5464
  Total Calories Burned: 181
  Average Hours of Sleep: 5.00

Week starting 2017-07-06:
  Total Steps: 6041
  Total Calories Burned: 197
  Average Hours of Sleep: 8.00

Week starting 2017-08-10:
  Total Steps: 25
  Total Calories Burned: 0
  Average Hours of Sleep: 5.00

Week starting 2017-09-07:
  Total Steps: 5461
  Total Calories Burned: 174
  Average Hours of Sleep: 4.00

Week starting 2017-10-05:
  Total Steps: 6915
  Total Calories Burned: 223
  Average Hours of Sleep: 5.00

Week starting 2017-10-12:
  Total Steps: 15116
  Total Calories Burned: 482
  Average Hours of Sleep: 6.17

Week starting 2017-10-19:
  Total Steps: 19524
  Total Calories Burned: 621
  Average Hours of Sleep: 5.71

Week starting 2017-10-26:
  Total Steps: 16055
  Total Calories Burned: 517
  Average Hours of Sleep: 6.14

Week starting 2017-11-02:
  Total Steps: 24977
  Total Calories Burned: 811
  Average Hours of Sleep: 3.86

Week starting

## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*